name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check the code format
        run: npm run fmt-check

      - name: Check ESLint
        run: npm run lint

      - name: Build
        run: npm run build
